sudo: false
language: java
jdk: 
  - openjdk8
  - oraclejdk8

cache: 
  directories: 
    - $HOME/.m2
before_cache: 
  - "rm -Rf $HOME/.m2/repository/com/trainings"
env: 
  matrix: 
    - SPRING_BOOT_VERSION=2.0.5.RELEASE
install: 
  - "mvn install -DskipTests=true --batch-mode"
script: 
  - "mvn clean install -B"
  - "mvn verify -Dspring.version=$SPRING_BOOT_VERSION --batch-mode"